services:
  # Source
  # Oracle
  oracle-source:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-source
    environment:
      ORACLE_PWD: myPassword1!
    ports:
      - "1521:1521"
    volumes:
      - oracle_source_data:/opt/oracle/oradata
      - ./init.sql:/docker-entrypoint-initdb.d/setup/init.sql
      - ./:/working  
  # GoldenGate
  gg-source:
    image: container-registry.oracle.com/goldengate/goldengate-free
    container_name: gg-source
    environment:
      OGG_ADMIN_PWD: myPassword1!
    ports:
      - "8080:80"
    volumes:
      - gg_source_data:/u01/ogg

  # Target
  # Oracle
  # oracle_target:
  #   image: container-registry.oracle.com/database/express:21.3.0-xe
    # container_name: oracle-source
    # environment:
      # ORACLE_PWD: myPassword1!
  #   ports:
  #     - "1522:1521"
  #   volumes:
  #     - oracle_target_data:/opt/oracle/oradata

  # GoldenGate
  # gg_target:
  #   image: container-registry.oracle.com/goldengate/goldengate-free
  #   container_name: gg-target    
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - gg_target_data:/u01/ogg

volumes:
  oracle_source_data:
  gg_source_data:
  oracle_target_data:
  gg_target_data: