version: '3.8'

services:
  # Oracle Source Database
  oracle_source:
    image: gvenzl/oracle-xe
    container_name: oracle-source
    environment:
      - ORACLE_PASSWORD=Oracle123  # password for Oracle XE system accounts
    ports:
      - "1521:1521"  # Default Oracle port for source DB
    volumes:
      - oracle_source_data:/opt/oracle/oradata  # persistent storage for source DB
      - ./init.sql:/container-entrypoint-initdb.d/init.sql

  # Oracle Target Database
  oracle_target:
    image: gvenzl/oracle-xe
    container_name: oracle-target
    environment:
      - ORACLE_PASSWORD=Oracle123  # password for Oracle XE system accounts
    ports:
      - "1522:1521"  # Map to a different port for target DB
    volumes:
      - oracle_target_data:/opt/oracle/oradata  # persistent storage for target DB

  # GoldenGate for capturing changes from Oracle Source
  gg_source:
    image: container-registry.oracle.com/goldengate/goldengate-free
    container_name: gg-source    
    depends_on:
      - oracle_source
    ports:
      - "8080:80"  # GoldenGate source service port
      - "8443:443"
    volumes:
      - gg_source_data:/u01/ogg  # Persistent storage for GoldenGate source config

  # GoldenGate for applying changes to Oracle Target
  # gg_target:
  #   image: container-registry.oracle.com/goldengate/goldengate-free
  #   container_name: gg-target    
  #   depends_on:
  #     - oracle_target
  #     - gg_source
  #   ports:
  #     - "8081:80"  # GoldenGate target service port
  #   volumes:
  #     - gg_target_data:/u01/ogg  # Persistent storage for GoldenGate target config

volumes:
  oracle_source_data:
  oracle_target_data:
  gg_source_data:
  gg_target_data:
